package epoch_edge_operations_types

const (
	VERSION_UPDATE           = "VERSION_UPDATE"
	SLASH_UNSTAKE            = "SLASH_UNSTAKE"
	REMOVE_FROM_WAITING_ROOM = "REMOVE_FROM_WAITING_ROOM"
	WORKFLOW_UPDATE          = "WORKFLOW_UPDATE"
	UPDATE_RUBICON           = "UPDATE_RUBICON"
	STAKING_CONTRACT_CALL    = "STAKING_CONTRACT_CALL"
)
